{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "oriental-january",
   "metadata": {},
   "source": [
    "## Prepare papermill for schulung3.geomar.de\n",
    "\n",
    "    Make sure you have activated the correct kernel\n",
    "    Install kernel manually"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "urban-virginia",
   "metadata": {},
   "outputs": [],
   "source": [
    "# !python -m ipykernel install --user --name parcels-container_2021.03.17-6c459b7"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "reverse-columbia",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Available kernels:\n",
      "  python3    /opt/conda/share/jupyter/kernels/python3\n"
     ]
    }
   ],
   "source": [
    "!jupyter kernelspec list"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "professional-audio",
   "metadata": {},
   "source": [
    "### Run papermill on schulung3.geomar.de"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "successful-composition",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Input Notebook:  115_afox_extracttrackendsandpaths_plus_pathlength.ipynb\n",
      "Output Notebook: ../executed/115_afox_endtracks_plus_pathlength/115_afox_extracttrackendsandpaths_plus_pathlength_2016.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpm0sqdt01'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpk2hq1n6w'\n",
      "Executing:   0%|          | 0/76 [00:00<?, ?cell/s]Executing notebook with kernel: python3\n",
      "Executing: 100%|██████████| 76/76 [04:03<00:00, 11.58s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 76/76 [04:06<00:00,  3.24s/cell]\n",
      "Input Notebook:  115_afox_extracttrackendsandpaths_plus_pathlength.ipynb\n",
      "Output Notebook: ../executed/115_afox_endtracks_plus_pathlength/115_afox_extracttrackendsandpaths_plus_pathlength_2017.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpnpqu4bei'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp8_hh_ni8'\n",
      "Executing:   0%|          | 0/76 [00:00<?, ?cell/s]Executing notebook with kernel: python3\n",
      "Executing: 100%|██████████| 76/76 [04:00<00:00, 12.09s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 76/76 [04:03<00:00,  3.20s/cell]\n",
      "Input Notebook:  115_afox_extracttrackendsandpaths_plus_pathlength.ipynb\n",
      "Output Notebook: ../executed/115_afox_endtracks_plus_pathlength/115_afox_extracttrackendsandpaths_plus_pathlength_2018.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp8s9ixmgn'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpvknjxcno'\n",
      "Executing:   0%|          | 0/76 [00:00<?, ?cell/s]Executing notebook with kernel: python3\n",
      "Executing: 100%|██████████| 76/76 [03:40<00:00, 10.88s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 76/76 [03:43<00:00,  2.94s/cell]\n",
      "Input Notebook:  115_afox_extracttrackendsandpaths_plus_pathlength.ipynb\n",
      "Output Notebook: ../executed/115_afox_endtracks_plus_pathlength/115_afox_extracttrackendsandpaths_plus_pathlength_2019.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp1nuaao4l'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpzeyz0_7f'\n",
      "Executing:   0%|          | 0/76 [00:00<?, ?cell/s]Executing notebook with kernel: python3\n",
      "Executing: 100%|██████████| 76/76 [03:53<00:00, 10.53s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 76/76 [03:56<00:00,  3.11s/cell]\n"
     ]
    }
   ],
   "source": [
    "%%bash\n",
    "\n",
    "mkdir -p ../executed/115_afox_endtracks_plus_pathlength/\n",
    "\n",
    "for year in {2016..2019};\n",
    "do\n",
    "papermill 115_afox_extracttrackendsandpaths_plus_pathlength.ipynb \\\n",
    "        ../executed/115_afox_endtracks_plus_pathlength/115_afox_extracttrackendsandpaths_plus_pathlength_${year}.ipynb \\\n",
    "        -p year $year \\\n",
    "        -k python3\n",
    "done\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a0a91c43-06b9-4d10-86ea-bcd992c7f013",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
