{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "bearing-digest",
   "metadata": {},
   "source": [
    "## Prepare papermill for schulung3.geomar.de\n",
    "\n",
    "    Make sure you have activated the correct kernel\n",
    "    Install kernel manually"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "incoming-glass",
   "metadata": {},
   "outputs": [],
   "source": [
    "# !python -m ipykernel install --user --name parcels-container_2021.09.29-09ab0ce"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "strange-deputy",
   "metadata": {},
   "outputs": [],
   "source": [
    "# !jupyter kernelspec list"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "collected-sugar",
   "metadata": {},
   "source": [
    "### Run papermill on schulung3.geomar.de"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "supposed-strike",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_1990.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp8u07wvln'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp6apkznwi'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [02:17<00:00,  4.08s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [02:19<00:00,  2.25s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_1991.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpa41mucyq'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmppubvaxan'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [02:21<00:00,  4.12s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [02:23<00:00,  2.31s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_1992.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp6h8b4a5e'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp71roloek'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [02:29<00:00,  3.95s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [02:31<00:00,  2.45s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_1993.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp9j0f67qx'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpc_831vf9'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [02:16<00:00,  3.88s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [02:18<00:00,  2.23s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_1994.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpd7v81lwx'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp3p_nya2n'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [02:25<00:00,  3.38s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [02:27<00:00,  2.38s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_1995.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpkf_ybood'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpbfh20acy'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [02:04<00:00,  3.86s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [02:06<00:00,  2.05s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_1996.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpyfa9hld9'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpgz_dd3sf'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [02:16<00:00,  4.03s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [02:18<00:00,  2.23s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_1997.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp1wd0hfoz'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp_scf4eot'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [02:17<00:00,  4.08s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [02:19<00:00,  2.25s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_1998.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpsckv4s88'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpalbud6p6'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [02:15<00:00,  3.79s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [02:18<00:00,  2.23s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_1999.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpo5hhk9it'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp4oegkb1g'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [02:26<00:00,  3.94s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [02:28<00:00,  2.39s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_2000.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp5ofafagc'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpxfdjwdo1'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [02:10<00:00,  3.87s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [02:12<00:00,  2.14s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_2001.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp8mrx2buu'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpfs_wk1d5'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [02:19<00:00,  3.80s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [02:22<00:00,  2.29s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_2002.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpxtzg5gmd'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpje1vk43d'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [02:12<00:00,  3.94s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [02:14<00:00,  2.17s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_2003.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpneoac_se'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpv98c2g3v'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [02:26<00:00,  3.71s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [02:28<00:00,  2.39s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_2004.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpzuudkszy'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp3aafimft'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [02:22<00:00,  3.41s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [02:24<00:00,  2.33s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_2005.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp3vyh7ksc'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpuwjm4cg9'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [01:26<00:00,  2.14s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [01:28<00:00,  1.42s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_2006.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpql00lzv_'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp3taleunk'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [01:34<00:00,  3.29s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [01:36<00:00,  1.56s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_2007.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpbcnhb4gv'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmprbb1mldj'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [01:37<00:00,  2.41s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [01:39<00:00,  1.61s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_2008.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpjdazxidw'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpvza99jfb'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [01:36<00:00,  3.64s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [01:38<00:00,  1.59s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_2009.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp_zlfmrn0'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp2i3k0apc'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [01:28<00:00,  2.18s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [01:30<00:00,  1.46s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_2010.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpva47_1hx'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpqabn9cq4'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [01:38<00:00,  3.71s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [01:40<00:00,  1.62s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_2011.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp3ffm1t__'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpboepd90m'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [01:46<00:00,  3.22s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [01:48<00:00,  1.75s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_2012.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpjycemqgq'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpspq4tqfg'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [01:37<00:00,  3.66s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [01:40<00:00,  1.62s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_2013.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpl9vuhd4s'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpvb7q7vt8'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [01:42<00:00,  3.10s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [01:45<00:00,  1.69s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_2014.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp2aytveo4'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpfq4v1v11'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [01:35<00:00,  3.31s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [01:37<00:00,  1.58s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_2015.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpbl5ib1ye'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpa_htfh6r'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [01:37<00:00,  2.58s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [01:39<00:00,  1.61s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_2016.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpqmq2_jja'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpgd5nvy3p'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [01:34<00:00,  3.22s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [01:37<00:00,  1.57s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_2017.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp4hbq_gd0'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmp9mtb9ppb'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [01:35<00:00,  2.46s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [01:37<00:00,  1.57s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_2018.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpvavlrua2'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpqmi7algr'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [01:35<00:00,  3.67s/cell]distributed.worker - WARNING - Heartbeat to scheduler failed\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [01:38<00:00,  1.59s/cell]\n",
      "Input Notebook:  207_afox_heat_and_freshwater_flux_labrador_sea.ipynb\n",
      "Output Notebook: ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_2019.ipynb\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/Grammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpkk3f6sgg'\n",
      "Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt\n",
      "Writing grammar tables to /gxfs_home/geomar/smomw122/.cache/black/21.9b0/PatternGrammar3.8.10.final.0.pickle\n",
      "Writing failed: [Errno 2] No such file or directory: '/gxfs_home/geomar/smomw122/.cache/black/21.9b0/tmpeba2iu8h'\n",
      "Executing:   0%|          | 0/62 [00:00<?, ?cell/s]Executing notebook with kernel: python\n",
      "Executing: 100%|██████████| 62/62 [01:40<00:00,  2.06s/cell]/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'wait_for' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/opt/conda/lib/python3.8/site-packages/distributed/client.py:4716: RuntimeWarning: coroutine 'Client._close' was never awaited\n",
      "  c.close(timeout=3)\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "Executing: 100%|██████████| 62/62 [01:42<00:00,  1.66s/cell]\n"
     ]
    }
   ],
   "source": [
    "%%bash\n",
    "\n",
    "mkdir -p \"../executed/207_afox_heat_and_freshwater_flux_labrador_sea/\"\n",
    "\n",
    "for year in {1990..2019};\n",
    "do\n",
    "papermill 207_afox_heat_and_freshwater_flux_labrador_sea.ipynb \\\n",
    "        ../executed/207_afox_heat_and_freshwater_flux_labrador_sea/207_afox_heat_and_freshwater_flux_labrador_sea_${year}.ipynb \\\n",
    "        -p year $year \\\n",
    "        -p mean_period \"5d\" \\\n",
    "        -k python\n",
    "done\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
